In [1]:
import numpy as np
from TicTacToe import TicTacToeGame
np.__version__

'2.2.3'

In [2]:
game = TicTacToeGame()
player = 1

while True:
    print(game, flush=True)
    valid_moves = game.get_valid_moves()
    print("valid_moves", [i for i in range(game.action_size) if valid_moves[i] == 1])
    try:
        response = input(f"{player}:").strip()
        action = int(response)
    except ValueError:
        if response == "q" or "":
            break
        print(f"Your input: {response} (numbers only). Press q to quit.")
        continue
    except EOFError:
        break

    if valid_moves[action] == 0:
        print("action not valid")
        continue

    game.make_move(action, player)
    value, terminated = game.get_value_and_terminated(action)

    if terminated:
        print(game)
        if value == 1:
            print(player, "won")
        else:
            print("draw")
        break
    
    player = game.get_opponent(player)


[[0 0 0]
 [0 0 0]
 [0 0 0]]
valid_moves [0, 1, 2, 3, 4, 5, 6, 7, 8]
[[0 0 0]
 [0 1 0]
 [0 0 0]]
valid_moves [0, 1, 2, 3, 5, 6, 7, 8]
action not valid
[[0 0 0]
 [0 1 0]
 [0 0 0]]
valid_moves [0, 1, 2, 3, 5, 6, 7, 8]
[[-1  0  0]
 [ 0  1  0]
 [ 0  0  0]]
valid_moves [1, 2, 3, 5, 6, 7, 8]
[[-1  0  1]
 [ 0  1  0]
 [ 0  0  0]]
valid_moves [1, 3, 5, 6, 7, 8]
[[-1 -1  1]
 [ 0  1  0]
 [ 0  0  0]]
valid_moves [3, 5, 6, 7, 8]
[[-1 -1  1]
 [ 0  1  0]
 [ 1  0  0]]
1 won
